version: '3.7'

services:

  bellybutton:
    build:
      context: ./services/bellybutton
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@bellybutton-db:5432/bellybutton
    depends_on:
      - bellybutton-db

  bellybutton-db:
    build:
      context: ./services/bellybutton/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - bellybutton
